# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_content', models.CharField(max_length=200)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
    ]
